## Student Retention Project

### Overview

This longitudinal panel dataset is designed to support predictive modeling, risk profiling, and machine learning research focused on higher-education student retention.

It contains 79,239 synthetic semester-level records, tracking students across multiple academic terms for up to 8 semesters. The dataset captures a holistic view of the student experience by combining:

* Demographic information
* Socioeconomic and financial constraints
* Academic performance
* Semester-level progression
* Learning engagement indicators
* Attrition and retention risk factors

The primary objective is to model the probability of future student attrition through the target variable:
`Target_Dropout_Next_Sem`


Data set could be found at: https://www.kaggle.com/datasets/razanihababdellatif/student-retention-and-academic-performance-data

In [1]:
import pandas as pd

### Read data set from CSV

In [7]:
# Read CSV
CSV_PATH = "academic_survival_longitudinal.csv"

df = pd.read_csv(CSV_PATH)
print("Data set shape (rows, cols): ", df.shape)

display(df.head())

Data set shape (rows, cols):  (79239, 22)

,Student_ID,Age,Gender,First_Generation,Family_Income,Household_Size,Housing_Status,Scholarship,Tuition_Base,Semester,...,Emergency_Expense,Sem_GPA,Attendance,LMS_Logins,Advising_Visits,Failed_Courses,Financial_Stress,Target_Dropout_Next_Sem,End_of_Semester_Status,Censored
0,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,1,...,0.0,2.85,85.8,67.0,0,0,1.7,0,Enrolled,0
1,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,2,...,0.0,2.73,81.0,89.0,1,0,3.1,0,Enrolled,0
2,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,3,...,0.0,2.60,78.3,60.0,0,2,3.0,0,Enrolled,0
3,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,4,...,0.0,2.34,77.2,59.0,2,3,5.1,0,Enrolled,0
4,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,5,...,0.0,1.90,79.3,53.0,1,2,3.6,0,Enrolled,1

### Data cleaning and processing

In this section we review the dataset columns and perform any necessary cleaning steps. We display the data types and check for the missing values and do small transformations if that is the case.

In [8]:
# Display data information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79239 entries, 0 to 79238
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               79239 non-null  object
 1   Age                      79239 non-null  int64
 2   Gender                   79239 non-null  object
 3   First_Generation         79239 non-null  int64
 4   Family_Income            75635 non-null  float64
 5   Household_Size           79239 non-null  int64
 6   Housing_Status           79239 non-null  object
 7   Scholarship              79239 non-null  int64
 8   Tuition_Base             79239 non-null  int64
 9   Semester                 79239 non-null  int64
 10  Course_Load              79239 non-null  int64
 11  Work_Hours               79239 non-null  float64
 12  Emergency_Expense        79239 non-null  float64
 13  Sem_GPA                  79239 non-null  float64
 14  Attendance               79239 non-null  float64
 15  LMS_Logins               78372 non-null  float64
 16  Advising_Visits          79239 non-null  int64
 17  Failed_Courses           79239 non-null  int64
 18  Financial_Stress         79239 non-null  float64
 19  Target_Dropout_Next_Sem  79239 non-null  int64
 20  End_of_Semester_Status   79239 non-null  object
 21  Censored                 79239 non-null  int64
dtypes: float64(7), int64(11), object(4)
memory usage: 13.3+ MB

In [13]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing values based on columns: \n")
display(missing_values[missing_values > 0])

Missing values based on columns:

Family_Income    3604
LMS_Logins        867
dtype: int64